apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicename.name }}
  namespace: {{ .Values.servicename.namespace }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: {{ .Values.servicename.name }}